program saadmin;

uses
  Vcl.Forms,
  Main.View in 'Views\Main.View.pas' {FMainView},
  Base.View in 'Views\Base\Base.View.pas' {FBaseView},
  BaseList.View in 'Views\Base\BaseList.View.pas' {FBaseListView},
  BaseRegister.View in 'Views\Base\BaseRegister.View.pas' {FBaseRegisterView},
  BaseMessage.View in 'Views\Base\BaseMessage.View.pas' {FBaseMessageView},
  BaseSearch.View in 'Views\Base\BaseSearch.View.pas' {FBaseSearchView},
  BaseReport.View in 'Views\Base\BaseReport.View.pas' {FBaseReportView},
  MSG0001.View in 'Views\Messages\MSG0001.View.pas' {FMSG0001View},
  MSG0002.View in 'Views\Messages\MSG0002.View.pas' {FMSG0002View},
  MSG0003.View in 'Views\Messages\MSG0003.View.pas' {FMSG0003View},
  MSG0004.View in 'Views\Messages\MSG0004.View.pas' {FMSG0004View},
  Types.Controllers in 'Controllers\Types\Types.Controllers.pas',
  Base.View.interf in 'Views\Base\Base.View.interf.pas',
  MessagesFactory.View.Interf in 'Views\Messages\MessagesFactory.View.Interf.pas',
  Types.Views in 'Views\Types\Types.Views.pas',
  MessagesFactory.View in 'Views\Messages\MessagesFactory.View.pas',
  Facade.View.interf in 'Views\Facade.View.interf.pas',
  Facade.View in 'Views\Facade.View.pas',
  Connection.Model.Interf in 'Models\Connection\Connection.Model.Interf.pas',
  DataMFirebird.Model in 'Models\Connection\Firebird\DataMFirebird.Model.pas' {FDataMFirebird: TDataModule},
  ConnectionFactory.Model.Interf in 'Models\Connection\ConnectionFactory.Model.Interf.pas',
  ConnectionFactory.Model in 'Models\Connection\ConnectionFactory.Model.pas',
  ConnectionSettings.Model.interf in 'Models\Settings\Connection\ConnectionSettings.Model.interf.pas',
  ConnectionSettings.Model in 'Models\Settings\Connection\ConnectionSettings.Model.pas',
  SettingsFactory.Model.interf in 'Models\Settings\SettingsFactory.Model.interf.pas',
  SettingsFactory.Model in 'Models\Settings\SettingsFactory.Model.pas',
  Facade.Model.Interf in 'Models\Facade.Model.Interf.pas',
  Facade.Model in 'Models\Facade.Model.pas',
  Types.Models in 'Models\Types\Types.Models.pas',
  Connection.Controller.interf in 'Controllers\Connection\Connection.Controller.interf.pas',
  Connection.Controller in 'Controllers\Connection\Connection.Controller.pas',
  Facade.Controller.Interf in 'Controllers\Facade.Controller.Interf.pas',
  Facade.Controller in 'Controllers\Facade.Controller.pas',
  TMNGDISTRICT.Entity.Model in 'Models\Modules\Managment\Districts\Entity\TMNGDISTRICT.Entity.Model.pas',
  Districts.Model.Interf in 'Models\Modules\Managment\Districts\Districts.Model.Interf.pas',
  Districts.Model in 'Models\Modules\Managment\Districts\Districts.Model.pas',
  ManagmentFactory.Model.Interf in 'Models\Modules\Managment\ManagmentFactory.Model.Interf.pas',
  ManagmentFactory.Model in 'Models\Modules\Managment\ManagmentFactory.Model.pas',
  ModulesFacade.Model.Interf in 'Models\Modules\ModulesFacade.Model.Interf.pas',
  ModulesFacade.Model in 'Models\Modules\ModulesFacade.Model.pas',
  District.Controller.Interf in 'Controllers\Modules\Managment\District\District.Controller.Interf.pas',
  District.Controller in 'Controllers\Modules\Managment\District\District.Controller.pas',
  DistrictInsert.Controller in 'Controllers\Modules\Managment\District\Operations\DistrictInsert.Controller.pas',
  ManagmentFactory.Controller.interf in 'Controllers\Modules\Managment\ManagmentFactory.Controller.interf.pas',
  ManagmentFactory.Controller in 'Controllers\Modules\Managment\ManagmentFactory.Controller.pas',
  ModulesFacade.Controller.interf in 'Controllers\Modules\ModulesFacade.Controller.interf.pas',
  ModulesFacade.Controller in 'Controllers\Modules\ModulesFacade.Controller.pas',
  MNG0001AView in 'Views\Modules\Managment\District\MNG0001AView.pas' {FMNG0001AView},
  ManagmentFactory.View.Interf in 'Views\Modules\Managment\ManagmentFactory.View.Interf.pas',
  ManagmentFactory.View in 'Views\Modules\Managment\ManagmentFactory.View.pas',
  ModulesFacade.View.Interf in 'Views\Modules\ModulesFacade.View.Interf.pas',
  ModulesFacade.View in 'Views\Modules\ModulesFacade.View.pas',
  MNG0001BView in 'Views\Modules\Managment\District\MNG0001BView.pas' {FMNG0001BView},
  DistrictUpdate.Controller in 'Controllers\Modules\Managment\District\Operations\DistrictUpdate.Controller.pas',
  DistrictDelete.Controller in 'Controllers\Modules\Managment\District\Operations\DistrictDelete.Controller.pas',
  DistrictDuplicate.Controller in 'Controllers\Modules\Managment\District\Operations\DistrictDuplicate.Controller.pas',
  TMNGCOUNTRY.Entity.Model in 'Models\Modules\Managment\Country\Entity\TMNGCOUNTRY.Entity.Model.pas',
  Country.Model.Interf in 'Models\Modules\Managment\Country\Country.Model.Interf.pas',
  Country.Model in 'Models\Modules\Managment\Country\Country.Model.pas',
  Country.Controller.Interf in 'Controllers\Modules\Managment\Country\Country.Controller.Interf.pas',
  Country.Controller in 'Controllers\Modules\Managment\Country\Country.Controller.pas',
  CountryInsert.Controller in 'Controllers\Modules\Managment\Country\Operations\CountryInsert.Controller.pas',
  MNG0002AView in 'Views\Modules\Managment\Country\MNG0002AView.pas' {FMNG0002AView},
  MNG0002BView in 'Views\Modules\Managment\Country\MNG0002BView.pas' {FMNG0002BView},
  MNG0003AView in 'Views\Modules\Managment\State\MNG0003AView.pas' {FMNG0003AView},
  CountryUpdate.Controller in 'Controllers\Modules\Managment\Country\Operations\CountryUpdate.Controller.pas',
  CountryDelete.Controller in 'Controllers\Modules\Managment\Country\Operations\CountryDelete.Controller.pas',
  CountryDuplicate.Controller in 'Controllers\Modules\Managment\Country\Operations\CountryDuplicate.Controller.pas',
  TMNGSTATE.Entity.Model in 'Models\Modules\Managment\State\Entity\TMNGSTATE.Entity.Model.pas',
  State.Model.Interf in 'Models\Modules\Managment\State\State.Model.Interf.pas',
  State.Model in 'Models\Modules\Managment\State\State.Model.pas',
  State.Controller.Interf in 'Controllers\Modules\Managment\State\State.Controller.Interf.pas',
  State.Controller in 'Controllers\Modules\Managment\State\State.Controller.pas',
  StateInsert.Controller in 'Controllers\Modules\Managment\State\Operations\StateInsert.Controller.pas',
  StateUpdate.Controller in 'Controllers\Modules\Managment\State\Operations\StateUpdate.Controller.pas',
  StateDelete.Controller in 'Controllers\Modules\Managment\State\Operations\StateDelete.Controller.pas',
  StateDuplicate.Controller in 'Controllers\Modules\Managment\State\Operations\StateDuplicate.Controller.pas',
  MNG0003BView in 'Views\Modules\Managment\State\MNG0003BView.pas' {FMNG0003BView},
  MNG0002CView in 'Views\Modules\Managment\Country\MNG0002CView.pas' {FMNG0002CView},
  TMNGCITY.Entity.Model in 'Models\Modules\Managment\City\Entity\TMNGCITY.Entity.Model.pas',
  City.Model.Interf in 'Models\Modules\Managment\City\City.Model.Interf.pas',
  City.Model in 'Models\Modules\Managment\City\City.Model.pas',
  City.Controller.Interf in 'Controllers\Modules\Managment\City\City.Controller.Interf.pas',
  City.Controller in 'Controllers\Modules\Managment\City\City.Controller.pas',
  CityInsert.Controller in 'Controllers\Modules\Managment\City\Operations\CityInsert.Controller.pas',
  CityUpdate.Controller in 'Controllers\Modules\Managment\City\Operations\CityUpdate.Controller.pas',
  CityDelete.Controller in 'Controllers\Modules\Managment\City\Operations\CityDelete.Controller.pas',
  CityDuplicate.Controller in 'Controllers\Modules\Managment\City\Operations\CityDuplicate.Controller.pas',
  Utils.Controller.Interf in 'Controllers\Utils\Utils.Controller.Interf.pas',
  Utils.Controller in 'Controllers\Utils\Utils.Controller.pas',
  Constants.Controller in 'Controllers\Utils\Constants.Controller.pas',
  REC0001AView in 'Views\Modules\Receive\Client\REC0001AView.pas' {FREC0001AView},
  MNG0004AView in 'Views\Modules\Managment\City\MNG0004AView.pas' {FMNG0004AView},
  MNG0004BView in 'Views\Modules\Managment\City\MNG0004BView.pas' {FMNG0004BView},
  MNG0003CView in 'Views\Modules\Managment\State\MNG0003CView.pas' {FMNG0003CView},
  MNG0004CView in 'Views\Modules\Managment\City\MNG0004CView.pas' {FMNG0004CView},
  TMNGCOMPANY.Entity.Model in 'Models\Modules\Managment\Company\Entity\TMNGCOMPANY.Entity.Model.pas',
  Company.Model.Interf in 'Models\Modules\Managment\Company\Company.Model.Interf.pas',
  Company.Model in 'Models\Modules\Managment\Company\Company.Model.pas',
  Company.Controller.Interf in 'Controllers\Modules\Managment\Company\Company.Controller.Interf.pas',
  Company.Controller in 'Controllers\Modules\Managment\Company\Company.Controller.pas',
  CompanyInsert.Controller in 'Controllers\Modules\Managment\Company\Operations\CompanyInsert.Controller.pas',
  CompanyUpdate.Controller in 'Controllers\Modules\Managment\Company\Operations\CompanyUpdate.Controller.pas',
  CompanyDelete.Controller in 'Controllers\Modules\Managment\Company\Operations\CompanyDelete.Controller.pas',
  CompanyDuplicate.Controller in 'Controllers\Modules\Managment\Company\Operations\CompanyDuplicate.Controller.pas',
  MNG0005AView in 'Views\Modules\Managment\Company\MNG0005AView.pas' {FMNG0005AView},
  MNG0005BView in 'Views\Modules\Managment\Company\MNG0005BView.pas' {FMNG0005BView},
  MNG0001CView in 'Views\Modules\Managment\District\MNG0001CView.pas' {FMNG0001CView},
  BCrypt.Controller in 'Controllers\Utils\BCrypt.Controller.pas',
  TMNGUSER.Entity.Model in 'Models\Modules\Managment\User\Entity\TMNGUSER.Entity.Model.pas',
  User.Model.Interf in 'Models\Modules\Managment\User\User.Model.Interf.pas',
  User.Model in 'Models\Modules\Managment\User\User.Model.pas',
  User.Controller.Interf in 'Controllers\Modules\Managment\User\User.Controller.Interf.pas',
  User.Controller in 'Controllers\Modules\Managment\User\User.Controller.pas',
  UserInsert.Controller in 'Controllers\Modules\Managment\User\Operations\UserInsert.Controller.pas',
  UserUpdate.Controller in 'Controllers\Modules\Managment\User\Operations\UserUpdate.Controller.pas',
  UserDelete.Controller in 'Controllers\Modules\Managment\User\Operations\UserDelete.Controller.pas',
  UserDuplicate.Controller in 'Controllers\Modules\Managment\User\Operations\UserDuplicate.Controller.pas',
  MNG0006AView in 'Views\Modules\Managment\User\MNG0006AView.pas' {FMNG0006AView},
  MNG0006BView in 'Views\Modules\Managment\User\MNG0006BView.pas' {FMNG0006BView},
  MSG0005.View in 'Views\Messages\MSG0005.View.pas' {FMSG0005View};

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TFMainView, FMainView);
  Application.Run;
end.
